### ISSUE TITLE
We are missing specs  around what is shown given different task statuses

### ISSUE THREAD

**Issue by tekin** [Crown-Commercial-Service/DataSubmissionService#51]
We skipped this in order to get https://trello.com/c/PCWRzFlK/182-users-know-the-status-of-their-tasks-from-their-task-list done, but we should revisit it.

**Comment by CristinaRO** [comment]
Do we need more specs around tasks? I don't want to just close it as a very old issue, but it's not clear without context what specs were missing.

**Comment by tekin** [comment]
Looking at the card and the [PR attached to](https://github.com/dxw/DataSubmissionService/pull/40/files) I would imagine this issue was created because the change in the PR doesn't contain any test coverage.
